[theme]
base="light"
primaryColor="#0d6efd"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f8f9fa"
textColor="#000000"
font="sans serif"

[theme]
base="dark"
primaryColor="#0d6efd"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"
font="sans serif"
