[theme]
primaryColor = "#2563EB"          # Azul principal
backgroundColor = "#FFFFFF"       # Fundo branco
secondaryBackgroundColor = "#F3F4F6"  # Cinza claro para painéis
textColor = "#1F2937"             # Texto cinza-escuro
font = "sans serif"                # Fonte limpa
